<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Slip Komisi</title>

    <style>
        @page {
            margin: 0;
        }

        body {
            font-family: DejaVu Sans, sans-serif;
            margin: 0;
            padding: 0;
            color: #1f2937;
            position: relative;
        }

        .background {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;

            background-image: url('{{ public_path('pdf-bg.png') }}');

            background-size: cover;
            background-position: center;

            opacity: 0.52;
        }

        .container {
            position: relative;
            z-index: 2;
        }

        .header {
            text-align: center;
            margin-bottom: 40px;
        }

        .logo {
            width: 90px;
            margin-bottom: 10px;
        }

        .title {
            font-size: 28px;
            font-weight: bold;
            color: #b45309;
        }

        .subtitle {
            color: #6b7280;
            font-size: 14px;
        }

        .card {
            width: 78%;
            margin: 30px auto 0 auto;

            background: rgba(255, 255, 255, 0.158);

            border-radius: 24px;

            padding: 35px;

            box-sizing: border-box;
        }

        .row {
            margin-bottom: 7px;
        }

        .label {
            font-size: 12px;
            color: #6b7280;
            margin-bottom: 4px;
        }

        .value {
            font-size: 16px;
            font-weight: bold;
        }

        .amount {
            font-size: 36px;
            font-weight: bold;
            color: #059669;
            margin-top: 20px;
        }

        .footer {
            position: absolute;
            bottom: 30px;
            left: 40px;
            right: 40px;
            text-align: center;
            font-size: 11px;
            color: #4c4c4c;
        }
    </style>
</head>

<body>
    <div class="background"></div>

    <div class="container">

        <div class="header">

            <img src="{{ public_path('logo-inv.png') }}" class="logo">

            <div class="title">
                Slip Komisi Partner
            </div>

            <div class="subtitle">
                Gem Pearls
            </div>

        </div>

        <div class="card">

            <div class="row">
                <div class="label">Partner</div>
                <div class="value">
                    {{ $commission->partner->name }}
                </div>
            </div>

            <div class="row">
                <div class="label">Tanggal</div>
                <div class="value">
                    {{ $commission->commission_date->format('d F Y') }}
                </div>
            </div>

            <div class="row">
                <div class="label">Total Belanja Tamu</div>
                <div class="value">
                    Rp {{ number_format($commission->total_sales, 0, ',', '.') }}
                </div>
            </div>

            <div class="row">
                <div class="label">Persentase Komisi</div>
                <div class="value">
                    {{ $commission->commission_rate }}%
                </div>
            </div>

            <div class="amount">
                Rp {{ number_format($commission->commission_amount, 0, ',', '.') }}
            </div>

        </div>

        <div
            style="
    margin-top:80px;
    width:78%;
    margin-left:auto;
    margin-right:auto;
    text-align:right;">
            <div style="font-size:14px;">
                Gem Pearls Jewelry
            </div>

            <div style="margin-top:60px; font-weight:bold;">
                ___________________
            </div>
        </div>

    </div>

    <div class="footer">
        Generated by Gem Pearls • {{ now()->format('d/m/Y H:i') }}
    </div>

</body>

</html>
